title: My experience as an Erasmus+ student in Finland
logo: P1060161.JPG
description: This is a homepage dedicated to my learning experience in this course.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
